# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'NativeStarterKit' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NativeStarterKit
  pod 'Firebase/Core'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase'
  pod 'Firebase/Auth'
  pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'BatchedBridge', # Required For React Native 0.45.0+
    'Core',
    # Add any other subspecs you want to use in your project
  ]

  target 'NativeStarterKit-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NativeStarterKitTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'NativeStarterKit-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NativeStarterKit-tvOS

end
